name: pre-release

on:
  push:
    branches:
      - master

jobs:
  win:
    name: Windows pre-release
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-mpg123
            vim
      - name: Checkout ProjectorRays
        uses: actions/checkout@v2
      - id: sha-short
        name: Get short SHA
        run: echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
      - name: Build
        run: |
          mingw32-make
          cp projectorrays.exe projectorrays-${{ steps.sha-short.outputs.sha-short }}.exe
      - name: Upload pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build ${{ steps.sha-short.outputs.sha-short }}
          files: projectorrays-${{ steps.sha-short.outputs.sha-short }}.exe
