name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  win:
    name: Windows release
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-mpg123
            vim
      - name: Checkout ProjectorRays
        uses: actions/checkout@v2
      - id: tag
        name: Get tag
        run: echo "::set-output name=tag::$(git describe --tags)"
      - name: Build
        run: |
          mingw32-make release
          cp projectorrays.exe projectorrays-${{ steps.tag.outputs.tag }}.exe
      - name: Upload release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: projectorrays-${{ steps.tag.outputs.tag }}.exe
